#!/bin/bash
riverctl keyboard-layout -rules evdev -model pc105 -options "grp:caps_toggle,compore:ralt" "us,ru"

riverctl spawn "killall waybar nm-applet &"
riverctl spawn "waybar -c ~/.config/waybar/config.jsonc -s ~/.config/waybar/style.css &"
riverctl spawn "nm-applet &"
riverctl map -layout 0 normal Super Return spawn alacritty
riverctl map  -layout 0 normal Super W close

riverctl map -layout 0 normal Super+Shift E exit
riverctl spawn "wlr-randr --output eDP-1 --scale 1.8"
riverctl map -layout 0 normal Super J focus-view next
riverctl map -layout 0 normal Super K focus-view previous
riverctl map -layout 0 normal Super Space focus-view next
riverctl map -layout 0 normal Super L focus-view next
riverctl map -layout 0 normal Super H focus-view previous

riverctl map -layout 0 normal Super+Shift J swap next
riverctl map -layout 0 normal Super+Shift K swap previous

riverctl map -layout 0 normal Super Comma focus-output previous

riverctl map -layout 0 normal Super+Shift Period send-to-output next
riverctl map -layout 0 normal Super+Shift Comma send-to-output previous


riverctl map -layout 0 normal Super+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map -layout 0 normal Super+Shift L send-layout-cmd rivertile "main-count -1"


riverctl map -layout 0 normal Super D spawn "wofi --show drun"

riverctl map -layout 0 normal Super+Alt+Control H snap left
riverctl map -layout 0 normal Super+Alt+Control J snap down
riverctl map -layout 0 normal Super+Alt+Control K snap up
riverctl map -layout 0 normal Super+Alt+Control L snap right

riverctl map -layout 0 normal Super+Alt+Shift H resize horizontal -100
riverctl map -layout 0 normal Super+Alt+Shift J resize vertical 100
riverctl map -layout 0 normal Super+Alt+Shift K resize vertical -100
riverctl map -layout 0 normal Super+Alt+Shift L resize horizontal 100

riverctl map -layout 0-pointer normal Super BTN_LEFT move-view

riverctl map -layout 0-pointer normal Super BTN_RIGHT resize-view

riverctl map -layout 0-pointer normal Super BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    riverctl map -layout 0 normal Super $i set-focused-tags $tags



    riverctl map -layout 0 normal Super+Shift $i set-view-tags $tags
done

all_tags=$(((1 << 32) - 1))
riverctl map -layout 0 normal Super 0 set-focused-tags $all_tags
riverctl map -layout 0 normal Super+Shift 0 set-view-tags $all_tags


riverctl map -layout 0 normal Super F toggle-fullscreen

riverctl map -layout 0 normal Super Up    send-layout-cmd rivertile "main-location top"
riverctl map -layout 0 normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map -layout 0 normal Super Down  send-layout-cmd rivertile "main-location bottom"
riverctl map -layout 0 normal Super Left  send-layout-cmd rivertile "main-location left"

riverctl declare-mode passthrough

riverctl map -layout 0 normal Super F11 enter-mode passthrough

riverctl map -layout 0 passthrough Super F11 enter-mode normal

for mode in normal locked
do
    riverctl map -layout 0 $mode None XF86Eject spawn 'eject -T'

    riverctl map -layout 0 $mode None XF86AudioRaiseVolume  spawn 'pamixer -i 5'
    riverctl map -layout 0 $mode None XF86AudioLowerVolume  spawn 'pamixer -d 5'
    riverctl map -layout 0 $mode None XF86AudioMute         spawn 'pamixer --toggle-mute'

    riverctl map -layout 0 $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map -layout 0 $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map -layout 0 $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map -layout 0 $mode None XF86AudioNext  spawn 'playerctl next'

    riverctl map -layout 0 $mode None XF86MonBrightnessUp   spawn 'brightnessctl set +5%'
    riverctl map -layout 0 $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
done
riverctl background-color 0x000000
riverctl border-color-focused 0x93a190
riverctl border-color-unfocused 0x586e75
riverctl border-width 0
riverctl focus-follows-cursor always
riverctl set-cursor-warp on-focus-change
riverctl set-repeat 50 300

riverctl rule-add -app-id 'float*' -title 'foo' float

riverctl rule-add -app-id "bar" csd
riverctl declare-mode launcher
riverctl map -layout 0 normal Super A enter-mode launcher
for i in $(seq 1 4) 
do
	riverctl map -layout 0 launcher None $i spawn "~/.config/river/launcher_$i.sh"
done
riverctl default-layout rivertile
rivertile -view-padding 0 -outer-padding 0 -main-ratio 0.5 -main-location left&
